name: discovery_ecr

on: 
  workflow_dispatch:
   inputs:
      environment:
        type: choice
        description: Environment
        required: true
        options:
          - dev-demo
          - dev2_eks
          - dev_eks
          - ci_eks
          - test_eks
          - stg_eks
          - prod_eks
      product_version:
         description: 'Put product version'
         # required: true
         default: 'v1.'
      product_name:
         description: 'Put product name'
         required: true
         default: 'discover_ecr'
  pull_request:
         
env:
  PRODUCT_NAME: ${{ github.event.inputs.product_name}}
  SCRIBE_PRODUCT_VERSION: ${{ github.event.inputs.product_version}}
  SCRIBE_URL: ${{ vars.SCRIBE_URL }}
  VALINT_SCRIBE_URL: ${{ vars.SCRIBE_URL }}
  SCRIBE_TOKEN: ${{ secrets.CLIENT_SECRET_AUTH }}
  AUTHOR_NAME: ALONA DODUKH
  AUTHOR_EMAIL: author@scribesecurity.com
  
        
jobs:
  build:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Generate version name 
        run: |
         export ECR_PRODUCT_VERSION="${{ env.SCRIBE_PRODUCT_VERSION }}-ecr_evidence_true"
         echo "ECR_PRODUCT_VERSION=$ECR_PRODUCT_VERSION" >> $GITHUB_ENV
         export ECR_PRODUCT_VERSION2="${{ env.SCRIBE_PRODUCT_VERSION }}-ecr_evidence_false"
         echo "ECR_PRODUCT_VERSION2=$ECR_PRODUCT_VERSION2" >> $GITHUB_ENV
         
      - name: Generate signed docker SBOM
        id: valint_bom_case1
        uses: scribe-security/action-bom@master
        with:
                target: mongo-express:latest
                format: attest
                attest-default: x509-env
                product-key: ${{ env.PRODUCT_NAME}}
                product-version: ${{env.ECR_PRODUCT_VERSION }}
                scribe-client-secret: ${{env.SCRIBE_TOKEN}}
                scribe-url: ${{env.SCRIBE_URL }}
        env:
            ATTEST_KEY: ${{secrets.ATTEST_KEY}}
            ATTEST_CERT: ${{secrets.ATTEST_CERT}}
            ATTEST_CA:  ${{secrets.ATTEST_CA}} 

      - name: Info Product
        run: |
            echo "Product ${{ env.PRODUCT_NAME}}"
            echo "Product Version ${{env.ECR_PRODUCT_VERSION}}"
            
      - name: Discovery evidence publish
        uses: scribe-security/action-platforms@SH-6474-merged-command
        with:
          command: discover
          platform: ecr
          sign: true
          evidence: true
          args: >-
            --scope.past_days 60
            --url ${{secrets.ECR_URL}}
            --aws-account.mapping 
            *::${{ env.PRODUCT_NAME}}::${{ env.ECR_PRODUCT_VERSION }}
            --repository.mapping
             *scribe-service*::${{ env.PRODUCT_NAME}}::${{ env.ECR_PRODUCT_VERSION }}
             
        env:
            ATTEST_KEY: ${{ secrets.ATTEST_KEY }}
            ATTEST_CERT: ${{ secrets.ATTEST_CERT}}
            ATTEST_CA:  ${{ secrets.ATTEST_CA }}
            VALINT_SCRIBE_URL: ${{env.SCRIBE_URL}}
            ECR_LOGIN_TOKEN: ${{secrets.ECR_TOKEN }}
            
      - name: Generate signed docker SBOM for case2
        id: valint_bom_case2
        uses: scribe-security/action-bom@master
        with:
                target: mongo-express:latest
                format: attest
                attest-default: x509-env
                product-key: ${{ env.PRODUCT_NAME}}
                product-version: ${{env.ECR_PRODUCT_VERSION2 }}
                scribe-client-secret: ${{env.SCRIBE_TOKEN}}
                scribe-url: ${{env.SCRIBE_URL }}
        env:
            ATTEST_KEY: ${{secrets.ATTEST_KEY}}
            ATTEST_CERT: ${{secrets.ATTEST_CERT}}
            ATTEST_CA:  ${{secrets.ATTEST_CA}} 

      - name: Info Product
        run: |
            echo "Product ${{ env.PRODUCT_NAME}}"
            echo "Product Version ${{env.ECR_PRODUCT_VERSION2}}"
            
      - name: Discovery not publish evidence
        uses: scribe-security/action-platforms@SH-6474-merged-command
        with:
          command: discover
          platform: ecr
          sign: true
          evidence: false
          args: >-
            --scope.past_days 60
            --url ${{secrets.ECR_URL}}
            --aws-account.mapping 
            *::${{ env.PRODUCT_NAME}}::${{ env.ECR_PRODUCT_VERSION2 }}
            --repository.mapping
             *scribe-service*::${{ env.PRODUCT_NAME}}::${{ env.ECR_PRODUCT_VERSION2 }}
             
        env:
            ATTEST_KEY: ${{ secrets.ATTEST_KEY }}
            ATTEST_CERT: ${{ secrets.ATTEST_CERT}}
            ATTEST_CA:  ${{ secrets.ATTEST_CA }}
            VALINT_SCRIBE_URL: ${{env.SCRIBE_URL}}
            ECR_LOGIN_TOKEN: ${{secrets.ECR_TOKEN }}

      
