name: discovery_gitlab

on: 
  workflow_dispatch:
   inputs:
      environment:
        type: choice
        description: Environment
        required: true
        options:
          - dev-demo
          - dev2_eks
          - dev_eks
          - ci_eks
          - test_eks
          - stg_eks
          - prod_eks
      product_version:
         description: 'Put product version'
         # required: true
         default: 'v1.'
      product_name:
         description: 'Put product name'
         required: true
         default: 'discover_gitlab'
  pull_request:
         
env:
  PRODUCT_NAME: "test_product"
  SCRIBE_PRODUCT_VERSION: "v1"
  SCRIBE_URL: ${{ vars.SCRIBE_URL }}
  VALINT_SCRIBE_URL: ${{ vars.SCRIBE_URL }}
  SCRIBE_TOKEN: ${{ secrets.CLIENT_SECRET_AUTH }}
  AUTHOR_NAME: ALONA DODUKH
  AUTHOR_EMAIL: author@scribesecurity.com
  
        
jobs:
  build:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Generate version name for each cl
        run: |
         export GL_PRODUCT_VERSION="${{ env.SCRIBE_PRODUCT_VERSION }}-gitlab"
         echo "GL_PRODUCT_VERSION=$GL_PRODUCT_VERSION" >> $GITHUB_ENV
         
      - name: Generate signed docker SBOM for docker mongo-express image
        id: gilab_case
        uses: scribe-security/action-bom@master
        with:
                target: busybox:latest
                format: attest
                attest-default: x509-env
                product-key: ${{ env.PRODUCT_NAME}}
                product-version: ${{env.GL_PRODUCT_VERSION }}
                scribe-client-secret: ${{env.SCRIBE_TOKEN}}
                scribe-url: ${{env.SCRIBE_URL }}
                
        env:
            ATTEST_KEY: ${{secrets.ATTEST_KEY}}
            ATTEST_CERT: ${{secrets.ATTEST_CERT}}
            ATTEST_CA:  ${{secrets.ATTEST_CA}} 

      - name: Info Product
        run: |
            echo "Product ${{ env.PRODUCT_NAME}}"
            echo "Product Version ${{env.GL_PRODUCT_VERSION}}"
            
      - name: Discovery Publish Evidence GitLab (Issue)
        uses: scribe-security/action-platforms@SH-6474-merged-command
        with:
          command: discover
          platform: gitlab
          evidence: true
          sign: true
          args: >-
            --scope.project Scribe-Test/integrations
            --scope.commit.past_days=60
            --organization.mapping 
            *::${{ env.PRODUCT_NAME}}::${{ env.GL_PRODUCT_VERSION }}
            --project.mapping
            *::${{ env.PRODUCT_NAME}}::${{ env.GL_PRODUCT_VERSION }}
        env:
            ATTEST_KEY: ${{ secrets.ATTEST_KEY }}
            ATTEST_CERT: ${{ secrets.ATTEST_CERT}}
            ATTEST_CA:  ${{ secrets.ATTEST_CA }}
            TOKEN: ${{ secrets.GL_TOKEN }}
            VALINT_SCRIBE_URL: ${{env.SCRIBE_URL}}

      
