name: discovery_github

on: 
  workflow_dispatch:
   inputs:
      environment:
        type: choice
        description: Environment
        required: true
        options:
          - dev-demo
          - dev2_eks
          - dev_eks
          - ci_eks
          - test_eks
          - stg_eks
          - prod_eks
      product_version:
         description: 'Put product version'
         # required: true
         default: 'v1.'
      product_name:
         description: 'Put product name'
         required: true
         default: 'discover_github'
  pull_request:
         
env:
  #PRODUCT_NAME: ${{ github.event.inputs.product_name}}
  #SCRIBE_PRODUCT_VERSION: ${{ github.event.inputs.product_version}}
  PRODUCT_NAME: "test_product"
  SCRIBE_PRODUCT_VERSION: "v1"
  # IMAGE_NAME: ${{ github.event.inputs.image_name}}
  SCRIBE_URL: ${{ vars.SCRIBE_URL }}
  VALINT_SCRIBE_URL: ${{ vars.SCRIBE_URL }}
  SCRIBE_TOKEN: ${{ secrets.CLIENT_SECRET_AUTH }}
  AUTHOR_NAME: ALONA DODUKH
  AUTHOR_EMAIL: author@scribesecurity.com
  
        
jobs:
  build:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Generate version name for each cl
        run: |
         export GH_PRODUCT_VERSION="${{ env.SCRIBE_PRODUCT_VERSION }}-github"
         echo "GH_PRODUCT_VERSION=$GH_PRODUCT_VERSION" >> $GITHUB_ENV
         export GL_PRODUCT_VERSION="${{ env.SCRIBE_PRODUCT_VERSION }}-gitlab"
         echo "GL_PRODUCT_VERSION=$GL_PRODUCT_VERSION" >> $GITHUB_ENV


         
      - name: Generate signed docker SBOM for docker mongo-express image
        id: valint_attest_file
        uses: scribe-security/action-bom@master
        with:
                # statement-cyclonedx-json, attest, 
                # type: docker
                target: busybox:latest
                # scribe-enable: true
                format: attest
                attest-default: x509-env
                product-key: ${{ env.PRODUCT_NAME}}
                product-version: ${{ env.GH_PRODUCT_VERSION }}
                scribe-client-secret: ${{ env.SCRIBE_TOKEN }}
                scribe-url: ${{env.SCRIBE_URL }}
                
        env:
            ATTEST_KEY: ${{secrets.ATTEST_KEY}}
            ATTEST_CERT: ${{secrets.ATTEST_CERT}}
            ATTEST_CA:  ${{secrets.ATTEST_CA}} 
            #     --scope.organization=scribe-security
            # --scope.repository *mongo* *scribe-training-vue-project

      - name: Info Product
        run: |
            echo "Product ${{ env.PRODUCT_NAME}}"
            echo "Product Version ${{env.GH_PRODUCT_VERSION}}"
            
      - name: Discovery Publish Evidence Github
        uses: scribe-security/action-platforms@SH-6474-merged-command
        with:
          command: discover
          platform: github
          evidence: true
          sign: true
          args: >-
            --scope.organization=scribedemo
            --scope.repository scribedemo/test_repository
            --workflow.skip --commit.skip --scope.branch=main
            --organization.mapping 
            *::${{ env.PRODUCT_NAME}}::${{ env.GH_PRODUCT_VERSION}}
            --repository.mapping
            *::${{ env.PRODUCT_NAME}}::${{env.GH_PRODUCT_VERSION}}
        env:
            ATTEST_KEY: ${{ secrets.ATTEST_KEY }}
            ATTEST_CERT: ${{ secrets.ATTEST_CERT}}
            ATTEST_CA:  ${{ secrets.ATTEST_CA }}
            GITHUB_TOKEN: ${{ secrets.ALONA_GITHUB_PAT }}
            VALINT_SCRIBE_URL: ${{env.SCRIBE_URL}}

      - name: Generate signed docker SBOM for docker mongo-express image
        id: gilab_case
        uses: scribe-security/action-bom@master
        with:
                # statement-cyclonedx-json, attest, 
                # type: docker
                target: busybox:latest
                # scribe-enable: true
                format: attest
                attest-default: x509-env
                product-key: ${{ env.PRODUCT_NAME}}
                product-version: ${{env.GL_PRODUCT_VERSION }}
                scribe-client-secret: ${{env.SCRIBE_TOKEN}}
                scribe-url: ${{env.SCRIBE_URL }}
                
        env:
            ATTEST_KEY: ${{secrets.ATTEST_KEY}}
            ATTEST_CERT: ${{secrets.ATTEST_CERT}}
            ATTEST_CA:  ${{secrets.ATTEST_CA}} 
            #     --scope.organization=scribe-security
            # --scope.repository *mongo* *scribe-training-vue-project

      - name: Info Product
        run: |
            echo "Product ${{ env.PRODUCT_NAME}}"
            echo "Product Version ${{env.GLPRODUCT_VERSION}}"
            
      - name: Discovery Publish Evidence Github
        uses: scribe-security/action-platforms@SH-6474-merged-command
        with:
          command: discover
          platform: gitlab
          evidence: true
          sign: true
          args: >-
            --scope.project Scribe-Test/integrations
            # --scope.repository scribedemo/test_repository
            # --workflow.skip --commit.skip --scope.branch=main
            --scope.commit.past_days=60
            --organization.mapping 
            *::${{ env.PRODUCT_NAME}}::${{ env.GL_PRODUCT_VERSION }}
            --project.mapping
            *::${{ env.PRODUCT_NAME}}::${{ env.GL_PRODUCT_VERSION }}
        env:
            ATTEST_KEY: ${{ secrets.ATTEST_KEY }}
            ATTEST_CERT: ${{ secrets.ATTEST_CERT}}
            ATTEST_CA:  ${{ secrets.ATTEST_CA }}
            TOKEN: glpat-C_iomXGsQDsBpRmCyqzx 
            VALINT_SCRIBE_URL: ${{env.SCRIBE_URL}}



