name: external_sig_x509_cert

on: 
  workflow_dispatch:
   inputs:
      environment:
        type: choice
        description: Environment
        required: true
        options:
          - dev-demo
          - dev2_eks
          - ci_eks
          - dev_eks
          - test_eks
          - stg_eks
          - prod_eks
      product_version:
         description: 'Put product version'
         required: false
         default: 'v1'
      product_name:
         description: 'Put product name'
         required: false
         default: 'External_files_sign_certificate_x509'

env:
        LOGICAL_APP_NAME: demo-project # The app name all these SBOMs will be assosiated with
        APP_VERSION: 1.0.1 # The app version all these SBOMs will be assosiated with
        # SBOM Author meta data - Optional
        AUTHOR_NAME: Alona Dodukh
        AUTHOR_EMAIL: alonadodukh@tetsemail.com
        AUTHOR_PHONE: 123-123-123-12345
        # SBOM Supplier meta data - Optional
        SUPPLIER_NAME: Scribe-Security 
        SUPPLIER_URL: www.scribesecurity.com 
        SUPPLIER_EMAIL: info@scribesecurity.com
        SUPPLIER_PHONE: 001-001-0011
        # URLs and product details
        PRODUCT_NAME: ${{ github.event.inputs.product_name }}
        PRODUCT_VERSION: ${{ github.event.inputs.product_version }}
        FILE: ${{ github.events.inputs.file }}
        SCRIBE_URL: ${{ vars.SCRIBE_URL }}
        SCRIBE_LOGIN_URL: ${{ vars.SCRIBE_LOGIN_URL }}
        SCRIBE_AUDIENCE: ${{ vars.SCRIBE_AUDIENCE }}

jobs:

 build:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    permissions:
        contents: read
        packages: write
        id-token: write

    steps:
        - uses: actions/checkout@v4

        - name: odeql.sarif.json with attest
          # uses: scribe-security/action-bom@master
          uses: scribe-security/action-evidence@master
          with:
                # type: file
                target: './codeql.sarif.json'
                # format: attest
                # attest-default: x509-env
                format: attest-generic
                scribe-enable: true
                components: packages,files,dep
                product-key: ${{env.PRODUCT_NAME}}
                product-version: ${{env.PRODUCT_VERSION}}
                scribe-client-secret: ${{ secrets.CLIENT_SECRET_AUTH}}
                scribe-url: ${{env.SCRIBE_URL}}
                scribe-auth-audience: ${{env.SCRIBE_AUDIENCE}}
                gate: github_action
                # deliverable: true
          env:
            ATTEST_KEY: ${{ secrets.ATTEST_KEY }}
            ATTEST_CERT: ${{ secrets.ATTEST_CERT }}
            ATTEST_CA:  ${{ secrets.ATTEST_CA}}
         
        - name: cyclonedx.json with statement
          # uses: scribe-security/action-bom@master
          uses: scribe-security/action-evidence@master
          with:
                # type: file
                target: './cyclonedx.json'
                format: attest-generic
                # attest-default: x509-env
                scribe-enable: true
                components: packages,files,dep
                product-key: ${{env.PRODUCT_NAME}}
                product-version: ${{env.PRODUCT_VERSION}}
                scribe-client-secret: ${{ secrets.CLIENT_SECRET_AUTH}}
                scribe-url: ${{env.SCRIBE_URL}}
                author-name: ${{env.AUTHOR_NAME}}
                author-email: ${{env.AUTHOR_EMAIL}}
                author-phone: ${{env.AUTHOR_PHONE}}
                supplier-name: ${{env.SUPPLIER_NAME}}
                supplier-url: ${{env.SUPPLIER_URL}}
                supplier-email: ${{env.SUPPLIER_EMAIL}} 
                supplier-phone: ${{env.SUPPLIER_PHONE}}
                gate: github_action 
                # deliverable: true 
                
        - name: SolarWinds 3rd
          # uses: scribe-security/action-bom@master
          uses: scribe-security/action-evidence@master
          with:
                # type: file
                target: './solarWinds_3rd.json'
                format: attest-generic
                # attest-default: x509-env
                scribe-enable: true
                # components: packages,files,dep
                product-key: ${{env.PRODUCT_NAME}}
                product-version: ${{env.PRODUCT_VERSION}}
                scribe-client-secret: ${{ secrets.CLIENT_SECRET_AUTH}}
                scribe-url: ${{env.SCRIBE_URL}}
                gate: github_action 
                # deliverable: true 
      
        - name: opshub.json with statement
          # uses: scribe-security/action-bom@master
          uses: scribe-security/action-evidence@master
          with:
                # type: file
                target: './opshub.json'
                format: statement
                # attest-default: x509-env
                scribe-enable: true
                product-key: ${{env.PRODUCT_NAME}}
                product-version: ${{env.PRODUCT_VERSION}}
                scribe-client-secret: ${{ secrets.CLIENT_SECRET_AUTH}}
                scribe-url: ${{env.SCRIBE_URL}}
                scribe-auth-audience: ${{env.SCRIBE_AUDIENCE}}
                gate: github_action 
                # deliverable: true
          env:
            ATTEST_KEY: ${{ secrets.ATTEST_KEY }}
            ATTEST_CERT: ${{ secrets.ATTEST_CERT }}
            ATTEST_CA:  ${{ secrets.ATTEST_CA}} 

        - name: snyk.sarif.json with attest
          # uses: scribe-security/action-bom@master
          uses: scribe-security/action-evidence@master
          with:
                # type: file
                target: './snyk.sarif.json'
                format: attest-generic
                # predicate-type: https://cyclonedx.org/bom
                # format: attest
                # attest-default: x509-env
                scribe-enable: true
                product-key: ${{env.PRODUCT_NAME}}
                product-version: ${{env.PRODUCT_VERSION}}
                scribe-client-secret: ${{ secrets.CLIENT_SECRET_AUTH}}
                scribe-url: ${{env.SCRIBE_URL}}
                scribe-auth-audience: ${{env.SCRIBE_AUDIENCE}}
                # components: packages,files,dep
                # author-name: ${{env.AUTHOR_NAME}}
                # author-email: ${{env.AUTHOR_EMAIL}}
                # author-phone: ${{env.AUTHOR_PHONE}}
                # supplier-name: ${{env.SUPPLIER_NAME}}
                # supplier-url: ${{env.SUPPLIER_URL}}
                # supplier-email: ${{env.SUPPLIER_EMAIL}} 
                # supplier-phone: ${{env.SUPPLIER_PHONE}}
                gate: github_action
          # env:
          #   ATTEST_KEY: ${{ secrets.ATTEST_KEY }}
          #   ATTEST_CERT: ${{ secrets.ATTEST_CERT }}
          #   ATTEST_CA:  ${{ secrets.ATTEST_CA}} 


        - name: snyk.cdx.json with attest
          # uses: scribe-security/action-bom@master
          uses: scribe-security/action-evidence@master
          with:
                # type: file
                target: './snyk.cdx.json'
                # predicate-type: https://cyclonedx.org/bom
                format: attest
                attest-default: x509-env
                scribe-enable: true
                product-key: ${{env.PRODUCT_NAME}}
                product-version: ${{env.PRODUCT_VERSION}}
                scribe-client-secret: ${{ secrets.CLIENT_SECRET_AUTH}}
                scribe-url: ${{env.SCRIBE_URL}}
                scribe-auth-audience: ${{env.SCRIBE_AUDIENCE}}
                # components: packages,files,dep
                # author-name: ${{env.AUTHOR_NAME}}
                # author-email: ${{env.AUTHOR_EMAIL}}
                # author-phone: ${{env.AUTHOR_PHONE}}
                # supplier-name: ${{env.SUPPLIER_NAME}}
                # supplier-url: ${{env.SUPPLIER_URL}}
                # supplier-email: ${{env.SUPPLIER_EMAIL}} 
                # supplier-phone: ${env.{SUPPLIER_PHONE}}
                deliverable: true
                gate: github_action
          env:
            ATTEST_KEY: ${{ secrets.ATTEST_KEY }}
            ATTEST_CERT: ${{ secrets.ATTEST_CERT }}
            ATTEST_CA:  ${{ secrets.ATTEST_CA}} 

       
        # - name: busybox:latest image
        #   # uses: scribe-security/action-bom@master
        #   uses: scribe-security/action-bom@master
        #   with:
        #         type: docker
        #         target: busybox:latest
        #         # predicate-type: https://cyclonedx.org/bom
        #         format: attest
        #         attest-default: x509-env
        #         scribe-enable: true
        #         components: packages,files,dep
        #         product-key: $PRODUCT_NAME
        #         product-version: $PRODUCT_VERSION
        #         scribe-client-id: ${{ secrets.CLIENT_ID }}
        #         scribe-client-secret: ${{ secrets.CLIENT_SECRET }}
        #         scribe-url: $SCRIBE_URL
        #         scribe-login-url: $SCRIBE_LOGIN_URL
        #         scribe-auth-audience: $SCRIBE_AUDIENCE 
        #         deliverable: true
        #   env:
        #     ATTEST_KEY: ${{ secrets.ATTEST_KEY }}
        #     ATTEST_CERT: ${{ secrets.ATTEST_CERT }}
        #     ATTEST_CA:  ${{ secrets.ATTEST_CA}}   
            
        - name: trivy.json with attest
          # uses: scribe-security/action-bom@master
          uses: scribe-security/action-evidence@master
          with:
                # type: file
                target: './trivy.json'
                # predicate-type: https://cyclonedx.org/bom
                format: attest
                attest-default: x509-env
                scribe-enable: true
                product-key: ${{env.PRODUCT_NAME}}
                product-version: ${{env.PRODUCT_VERSION}}
                scribe-client-secret: ${{ secrets.CLIENT_SECRET_AUTH}}
                scribe-url: ${{env.SCRIBE_URL}}
                # components: packages,files,dep
                # author-name: ${{env.AUTHOR_NAME}}
                # author-email: ${{env.AUTHOR_EMAIL}}
                # author-phone: ${{env.AUTHOR_PHONE}}
                # supplier-name: ${{env.SUPPLIER_NAME}}
                # supplier-url: ${{env.SUPPLIER_URL}}
                # supplier-email: ${{env.SUPPLIER_EMAIL}} 
                # supplier-phone: ${{env.SUPPLIER_PHONE}}
                deliverable: true
                gate: github_action
          env:
            ATTEST_KEY: ${{ secrets.ATTEST_KEY }}
            ATTEST_CERT: ${{ secrets.ATTEST_CERT }}
            ATTEST_CA:  ${{ secrets.ATTEST_CA}}   


        - name: trivy.sarif.json with statement
          # uses: scribe-security/action-bom@master
          uses: scribe-security/action-evidence@master
          with:
                # type: file
                target: './trivy.sarif.json'
                # predicate-type: https://cyclonedx.org/bom
                format: statement
                # attest-default: x509-env
                scribe-enable: true
                product-key: ${{env.PRODUCT_NAME}}
                product-version: ${{env.PRODUCT_VERSION}}
                scribe-client-secret: ${{ secrets.CLIENT_SECRET_AUTH}}
                scribe-url: ${{env.SCRIBE_URL}}
                # components: packages,files,dep
                # author-name: ${{env.AUTHOR_NAME}}
                # author-email: ${{env.AUTHOR_EMAIL}}
                # author-phone: ${{env.AUTHOR_PHONE}}
                # supplier-name: ${{env.SUPPLIER_NAME}}
                # supplier-url: ${{env.SUPPLIER_URL}}
                # supplier-email: ${{env.SUPPLIER_EMAIL}} 
                # supplier-phone: ${{env.SUPPLIER_PHONE}}
                deliverable: true
                gate: github_action
          env:
            ATTEST_KEY: ${{ secrets.ATTEST_KEY }}
            ATTEST_CERT: ${{ secrets.ATTEST_CERT }}
            ATTEST_CA:  ${{ secrets.ATTEST_CA}}      
        

        - name: Generate SLSA provenance statement
          id: valint_slsa_statement
          uses: scribe-security/action-bom@master
          with:
                # target: 'docker:${{ github.repository }}:${{ github.sha }}'
                target: './snyk.cdx.json'
                # predicate-type: https://cyclonedx.org/bom
                scribe-enable: true
                format: attest-slsa
                attest-default: x509-env
                product-key: ${{env.PRODUCT_NAME}}
                product-version: ${{env.PRODUCT_VERSION}}
                scribe-client-secret: ${{ secrets.CLIENT_SECRET_AUTH}}
                scribe-url: ${{env.SCRIBE_URL}}
                scribe-auth-audience: ${{env.SCRIBE_AUDIENCE}}
                # components: packages,files,dep
                # author-name: ${{env.AUTHOR_NAME}}
                # author-email: ${{env.AUTHOR_EMAIL}}
                # author-phone: ${{env.AUTHOR_PHONE}}
                # supplier-name: ${{env.SUPPLIER_NAME}}
                # supplier-url: ${{env.SUPPLIER_URL}}
                # supplier-email: ${{env.SUPPLIER_EMAIL}} 
                # supplier-phone: ${{env.SUPPLIER_PHONE}}
                # deliverable: true
                gate: github_action
          env:
            ATTEST_KEY: ${{ secrets.ATTEST_KEY }}
            ATTEST_CERT: ${{ secrets.ATTEST_CERT }}
            ATTEST_CA:  ${{ secrets.ATTEST_CA }}
  

        - uses: actions/upload-artifact@v4
          with:
                name: provenance
                path: ${{ steps.valint_slsa_statement.outputs.OUTPUT_PATH }}
        
